steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/psychbot-499512/cloud-run-source-deploy/bot-sleuthing-project/bot-sleuthing-project:$COMMIT_SHA
      - bot/

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-central1-docker.pkg.dev/psychbot-499512/cloud-run-source-deploy/bot-sleuthing-project/bot-sleuthing-project:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - jobs
      - update
      - bot-sleuthing-job
      - --image
      - us-central1-docker.pkg.dev/psychbot-499512/cloud-run-source-deploy/bot-sleuthing-project/bot-sleuthing-project:$COMMIT_SHA
      - --region
      - us-central1
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - jobs
      - execute
      - bot-sleuthing-job
      - --region
      - us-central1
    
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - jobs
      - update
      - bot-sleuthing-job
      - --image
      - us-central1-docker.pkg.dev/psychbot-499512/cloud-run-source-deploy/bot-sleuthing-project/bot-sleuthing-project:$COMMIT_SHA
      - --region
      - us-east1
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - jobs
      - execute
      - bot-sleuthing-job
      - --region
      - us-east1

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - jobs
      - update
      - bot-sleuthing-job
      - --image
      - us-central1-docker.pkg.dev/psychbot-499512/cloud-run-source-deploy/bot-sleuthing-project/bot-sleuthing-project:$COMMIT_SHA
      - --region
      - us-east4
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - jobs
      - execute
      - bot-sleuthing-job
      - --region
      - us-east4

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - jobs
      - update
      - bot-sleuthing-job
      - --image
      - us-central1-docker.pkg.dev/psychbot-499512/cloud-run-source-deploy/bot-sleuthing-project/bot-sleuthing-project:$COMMIT_SHA
      - --region
      - us-central5
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - jobs
      - execute
      - bot-sleuthing-job
      - --region
      - us-central5

images:
  - us-central1-docker.pkg.dev/psychbot-499512/cloud-run-source-deploy/bot-sleuthing-project/bot-sleuthing-project:$COMMIT_SHA
options:
  logging: CLOUD_LOGGING_ONLY